use_frameworks!
platform :ios, '12.0'

target 'RainbowColorPicker_Example' do
  pod 'RainbowColorPicker', :path => '../'

  target 'RainbowColorPicker_Tests' do
    inherit! :search_paths

    
  end
end
